# List of all card names (generated with a random name generation site: https://fr.fantasynamegenerators.com/noms-îles.php)

mapNames = [
'Yioggeonet',
'Biappopia',
'Paetegoth',
'Prearuphere',
'Clibixath',
'Obadolon',
'Aekkituary',
'Vriabover',
'Acheanor',
'Stiobbever',
'Udorona',
'Cheammethan',
'Itixath',
'Ophimelan',
'Cisivion',
'The Magic Empire',
'The Harsh Isles',
'The Perfect Isles',
'The Void Isles',
'The Rabid Isles',
'The Summer Terrain',
'The Crimson Country',
'The Amber Vales',
'The Gold Vales',
'The Diamond Vales',
'The Plains Vales',
'The Solitary Isle',
'The Savage World',
'The Rune World',
'The Empty Isles',]
